class Solution {
        public double findMedianSortedArrays(int[] nums1, int[] nums2) {

                // Always binary search on the smaller array
                        if (nums1.length > nums2.length) {
                                    return findMedianSortedArrays(nums2, nums1);
                                            }

                                                    int m = nums1.length;
                                                            int n = nums2.length;

                                                                    int left = 0;
                                                                            int right = m;

                                                                                    while (left <= right) {

                                                                                                int partitionA = left + (right - left) / 2;
                                                                                                            int partitionB = (m + n + 1) / 2 - partitionA;

                                                                                                                        int maxLeftA = (partitionA == 0)
                                                                                                                                            ? Integer.MIN_VALUE
                                                                                                                                                                : nums1[partitionA - 1];

                                                                                                                                                                            int minRightA = (partitionA == m)
                                                                                                                                                                                                ? Integer.MAX_VALUE
                                                                                                                                                                                                                    : nums1[partitionA];

                                                                                                                                                                                                                                int maxLeftB = (partitionB == 0)
                                                                                                                                                                                                                                                    ? Integer.MIN_VALUE
                                                                                                                                                                                                                                                                        : nums2[partitionB - 1];

                                                                                                                                                                                                                                                                                    int minRightB = (partitionB == n)
                                                                                                                                                                                                                                                                                                        ? Integer.MAX_VALUE
                                                                                                                                                                                                                                                                                                                            : nums2[partitionB];

                                                                                                                                                                                                                                                                                                                                        // Correct partition found
                                                                                                                                                                                                                                                                                                                                                    if (maxLeftA <= minRightB && maxLeftB <= minRightA) {

                                                                                                                                                                                                                                                                                                                                                                    // Odd total length
                                                                                                                                                                                                                                                                                                                                                                                    if ((m + n) % 2 == 1) {
                                                                                                                                                                                                                                                                                                                                                                                                        return Math.max(maxLeftA, maxLeftB);
                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                        // Even total length
                                                                                                                                                                                                                                                                                                                                                                                                                                                        return (Math.max(maxLeftA, maxLeftB)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                + Math.min(minRightA, minRightB)) / 2.0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Move left in nums1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (maxLeftA > minRightB) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    right = partitionA - 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Move right in nums1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        left = partitionA + 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    throw new IllegalArgumentException();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
}